dataレイヤーモジュールの新規作成
write18jack/AtleticoLineupApp pull request #11
Opened 2024-09-08 09:39 UTC by write18jack

dataレイヤーモジュールの作成を行いました。

branchは以下構成で作成しています。
・main
　・feature-create-multi-module
　　・create-data-module

[モジュール分け作業の状態](https://www.notion.so/Android-e1cc5b8a646e4a959a2c71fe0d875497?pvs=4#6c17fc5ce4c14ec6a774597cc1de5f2b)

以上です。ご確認よろしくお願いいたします。

2024-09-08 16:00 UTC, hayashitoshiki commented
> ・main
> 　・feature-create-multi-module
> 　　・create-data-module

と記載されているのに、取り込み先がmainに直接向いてそうです👀
`feature-createmutli-module`をpushして、`feature-createmutli-module`へmergeの向き先を変えてみましょう🙌

2024-09-08 16:12 UTC, hayashitoshiki requested changes
> ・main
> 　・feature-create-multi-module
> 　　・create-data-module

と記載されているのに、取り込み先がmainに直接向いてそうです👀
`feature-createmutli-module`をpushして、`feature-createmutli-module`へmergeの向き先を変えてみましょう🙌

2024-09-08 16:44 UTC, hayashitoshiki commented on data/src/androidTest/java/com/whitebeach/data/ExampleInstrumentedTest.kt
> +class ExampleInstrumentedTest {
このテストファイルはTODOで作られているだけで、実際使用はしないので消してしまて良さそうです🙆‍♂️

2024-09-08 16:44 UTC, hayashitoshiki commented on data/src/test/java/com/whitebeach/data/ExampleUnitTest.kt
> +class ExampleUnitTest {
こちらのテストファイルも同様です🙆‍♂️

2024-09-10 22:07 UTC, write18jack commented
> > ・main
> > 　・feature-create-multi-module
> > 　　・create-data-module
> 
> と記載されているのに、取り込み先がmainに直接向いてそうです👀 `feature-createmutli-module`をpushして、`feature-createmutli-module`へmergeの向き先を変えてみましょう🙌

edit でマージ先変更しました！

2024-09-10 23:20 UTC, hayashitoshiki commented
* https://github.com/write18jack/AtleticoLineupApp/pull/11#discussion_r1749291217
* https://github.com/write18jack/AtleticoLineupApp/pull/11#discussion_r1749291235

に関して、
修正したら解決済みにするのではなく、
それぞれのコメントに対して、修正したコミットを添付して、修正した旨報告しましょう！
ここも報相連の練習です👍
（でも、自分で色々調べて試してみた点は👍です）

大学のレポートを題材にして例えると、
下記のイメージです😄

`本来のやり取り `
1. コメントで指摘される
2. コメントで修正した旨返信する

↓

1. 教授に添削してもらって修正点を指摘される
2. 教授に修正した内容を添えて、修正した旨報告する


` 白濱君がやっていること `

1. コメントで指摘される
2. コメントをつけずに解決済みにする

↓

1. 教授に添削してもらって修正点を指摘される
2. 教授に確認を取らず（何も言わず）に、自分で解決しただろうと決めつけて完了させる

2024-09-10 23:21 UTC, hayashitoshiki reviewed
修正点コメントされたらapploveします🙆‍♂️

2024-09-11 15:37 UTC, write18jack commented on data/src/androidTest/java/com/whitebeach/data/ExampleInstrumentedTest.kt
> +class ExampleInstrumentedTest {
[ExampleInstrumentedTest](https://github.com/write18jack/AtleticoLineupApp/pull/11/commits/2a919ea0e33ef6c53e7ea7d5f57cb56b1501f6ed)を修正しました！
ご確認おねがいします。

2024-09-11 15:38 UTC, write18jack commented on data/src/test/java/com/whitebeach/data/ExampleUnitTest.kt
> +class ExampleUnitTest {
[ExampleUnitTest ](https://github.com/write18jack/AtleticoLineupApp/pull/11/commits/2a919ea0e33ef6c53e7ea7d5f57cb56b1501f6ed)を修正しました！
ご確認よろしくお願いいたします。

2024-09-11 15:48 UTC, hayashitoshiki approved these changes
お疲れ様でした🙌
OKです🙆‍♂️

2024-09-11 16:10 UTC, write18jack commented
> > > ・main
> > > 　・feature-create-multi-module
> > > 　　・create-data-module
> > 
> > 
> > と記載されているのに、取り込み先がmainに直接向いてそうです👀 `feature-createmutli-module`をpushして、`feature-createmutli-module`へmergeの向き先を変えてみましょう🙌
> 
> edit でマージ先変更しました！

2024-09-11 16:11 UTC, merged